development:
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5
  username: patron
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app
  pool: 5
  username: patron
  password: